  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      restart: on-failure 

    app:
      build: .
      image: app
      command: python manage.py runserver 0.0.0.0:8000
      env_file: &envfile
        - env.env
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - db
      depends_on:
        - migration
        - redis

    migration:
      build: .
      image: app-migrate
      command: python manage.py migrate
      volumes:
        - .:/code
      links:
        - db
      depends_on:
        - makemigration

    makemigration:
      build: .
      image: app-makemigrate
      command: python manage.py makemigrations
      volumes:
        - .:/code
      links:
        - db
      depends_on:
        - db

    celery:
      build: .
      image: app-image
      restart: "no"
      env_file: *envfile
      command: celery -A cyclone worker -l info
      volumes:
        - .:/code
      depends_on:
        - redis
        - db
        - app
      restart: on-failure

    celery-beat:
      build: .
      command: celery -A cyclone beat -l info
      volumes:
        - .:/code
      depends_on:
        - redis

    redis:
      image: redis:alpine

