  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      restart: on-failure 

    app:
      build: .
      image: app
      command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - db
      depends_on:
        - db
        - redis

    celery:
      build: .
      image: app-image
      command: celery -A cyclone worker -l info
      volumes:
        - .:/code
      depends_on:
        - redis
        - db
        - app
      restart: on-failure

    celery-beat:
      build: .
      command: celery -A cyclone beat -l info
      volumes:
        - .:/code
      depends_on:
        - redis

    redis:
      image: redis:alpine

